version: '3.8'
services:

  sqldb:
   container_name: sqldb
   image: mcr.microsoft.com/mssql/server:2019-latest   
   ports:
     - "1433:1433"
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=P@ssw0rd
     - SA_PASSWORD=P@ssw0rd
   # The volumes section is used to map directories from the host machine to directories inside the container. 
   # This allows for data persistence and sharing between the host and the container.
   volumes:
     - ./sqldata/:/var/opt/mssql/data/
     - ./sqllog/:/var/opt/mssql/log/
 
  dbapi:
    container_name: dbapi
    image: dbapi    
    build:
      context: .      
      dockerfile: dbapi/Dockerfile
    # 127.0.0.1:58441:80 maps host port 58441 to container port 80, but only accessible via 'localhost'.
    ports:
      - "58433:80"
      - "127.0.0.1:58441:80" 
    depends_on:
      - sqldb
    environment:
      - DB_HOST=host.docker.internal,1433
      - DB_NAME=crmdb
      - DB_SA_PASSWORD=P@ssw0rd
      - ASPNETCORE_ENVIRONMENT=Development

  web:
    container_name: web
    image: web
    build:
      context: .      
      dockerfile: web/Dockerfile
    ports:
       - "58432:80"
       - "127.0.0.1:58440:80" 
    depends_on:
       - dbapi
    environment:
      - DB_API_URL=host.docker.internal
      - HTTP_PORT=58441
      - ENVIRONMENT_FLAG=Development
